apiVersion: v1
kind: Service
metadata:
  name: movie-rentals-app-service
  namespace: movie-rentals-ns
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: movie-rentals-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-rentals-ingress
  namespace: movie-rentals-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: movie-rentals.<Ingress Controller IP>.nip.io
      http:
        paths:
          - backend:
              service:
                name: movie-rentals-app-service
                port:
                  number: 80
            path: /
            pathType: Prefix
